### ISSUE TITLE
Don't force update tofix list

### ISSUE THREAD

**Issue by bil-elmoussaoui** [Foggalong/hardcode-fixer#168]
Forcing the update makes the revert impossible as the user will always lose the modifications that might be done to tofix.csv like for hardcoded icons... the revert processus won't work as the current_icon name is hardcoded...

**Comment by Foggalong** [comment]
This is actually something we want to happen. The script originally worked by downloading it once to an install directory and reading from there but it got bogged down very quickly with packaging and functionally in cases of repeat use, automated setups, etc. We streamlined it down to one script so that now just does all the work.

Ideally we'd never remove or modify a line in the CSV, just add new ones. The exception to this is feature updates which are going to be few and very far between. Unless I've misunderstood what you're saying?
