### ISSUE TITLE
Some ideas

### ISSUE THREAD

**Issue by szekeres2016** [Foggalong/hardcode-fixer#273]
Good day, I have some ides to improve the script. Currently the script fixes the icons globally if run my sudo, but if there are multiple user accounts on the computer that can break icons for other users if they chose to use default icon themes or different ones. My idea is that the script should make a local copy of detected hardcoded icon files to "~/.local./share/applications/" and make the changes there. This will result in themed icons for the user with themes and default icons for everyone else. That way no root access is needed to fix anything globally, updates to the applications will not screw up the icons. It's my preferred way to fix the hard-coded icons and so far it really works great!

**Comment by bil-elmoussaoui** [comment]
This is already fixed by my old PR https://github.com/Foggalong/hardcode-fixer/pull/241
The fix was easy enough, as the default icons are copied to the /usr/share/icons/hicolor. This way even if you switch from your icon theme to the default one, the default icons will be shown. 
If you have any specific issue, please open a new issue
@Foggalong This can be closed :+1:
