### ISSUE TITLE
Icon missing in Solus

### ISSUE THREAD

**Issue by maxiclo** [Foggalong/hardcode-fixer#304]
![screenshot from 2017-09-03 09-49-48](https://user-images.githubusercontent.com/8681722/30001403-4781ed42-908d-11e7-932c-d6da6b2d0bb1.png)
![screenshot from 2017-09-03 09-50-31](https://user-images.githubusercontent.com/8681722/30001404-5e6c52d6-908d-11e7-8f20-9886f8b3a631.png)

As from attached screenshot file the following icons are missing in **Solus Software Center**:
Home: Programming Languages & Tools
Third Party Tab: Google Talk Plugin
Third Party Tab: Mendeley Desktop

Thanks in advance to consider this.

**Comment by Foggalong** [comment]
Few points:

1. hardcode-fixer doesn't provide those icons itself, it just makes it possible for other icon themes to theme them
2. This script only fixes the launchers for applications you have installed, rather than any given hardcoded icon in any given application interface. This is because the method of hardcoding varies differently from context to context and it would require an entirely different script for each one. For example, there's a different script [Hardcode-Tray](https://github.com/bil-elmoussaoui/Hardcode-Tray) which just fixes the hardcoded icons in the tray.
3. Even when you've installed the application and have the launcher, we need some details in order to make that fix (launcher filename, launcher icon line, etc).

Because the icons in the Solus Software centre are part of its interface, rather than local launchers for programs you've got installed this script can't fix them. Sorry!
