### ISSUE TITLE
Is this project still developed?

### ISSUE THREAD

**Issue by tiotrom** [Foggalong/hardcode-fixer#378]
I am wondering if it is worth reporting broken packages. I don't see any activity for the past 2-3 years....

**Comment by Foggalong** [comment]
> how is this script aware of what name/icon to use?

Quite simply, the script _isn't_ aware! All this script does is un-hardcode the launchers by changing `Icon=/path/to/app.png` to `Icon=app` and copying the original icon file from `/path/to/app.png` to the standard freedesktop location for icons so that the system picks it up. Any themes which have an icon called `app` will then appear for the hardcoded launcher. There's more information about this [in the wiki](https://github.com/Foggalong/hardcode-fixer/wiki/What,-Why-&-How)! :slightly_smiling_face:
