### ISSUE TITLE
cp: cannot create regular file

### ISSUE THREAD

**Issue by Foggalong** [Foggalong/hardcode-fixer#74]
Even though the launchers is correctly fixed, it throws this error whenever fixing a Steam (or Local?) app. It does this regardless of whether fixing in Local or Global mode and the same error does not occur when reverting

```bash
S: Fixing Bastion...
cp: cannot create regular file ‘/home/josh/.local/share/icons/hicolor/48x48/apps/steam_icon_107100.png’: No such file or directory
```

**Comment by hlechner** [comment]
Strange, It is working here, I'll check it

**Comment by Foggalong** [comment]
Ubuntu 14.10 utopic, all packages up to date. How about you? I know people had different bugs & issues with the script on Fedora and Arch so it wouldn't surprise me if this is the same

**Comment by hlechner** [comment]
In my case: Arch Linux. all updated also.

I've virtual machine here, so no problem I can test in Ubuntu

**Comment by Foggalong** [comment]
Thanks :D Your input is appreciated!

**Comment by hlechner** [comment]
So, I've tested with Ubuntu 14.10 in Live CD mode.

I could reproduce exactly the same error. but what is strange is because I receive this error in the new and the old one.

Here the command that was getting error:
```
cp /usr/share/icons/hicolor/48x48/apps/steam.png /home/ubuntu/.local/share/icons/hicolor/48x48/apps/
```

In my case what was happening is that the destination folder was not created. when I manually create the folder "/home/ubuntu/.local/share/icons/hicolor/48x48/apps/" the error was gone, and its start work.

@Foggalong Could you check if its your case? Just run the following command:
```
/home/josh/.local/share/icons/hicolor/48x48/apps/
```

And try it again.

**Comment by hlechner** [comment]
If it's the same issue as you're having, a possible solution is to check if folder exist, if not, mkdir

**Comment by Foggalong** [comment]
I'll test this asap :)
